apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: verttistenberg/week4cloudservices-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: WEATHER_API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: WEATHER_API_URL
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: WEATHER_API_KEY
            - name: FMI_API_URL
              value: https://opendata.fmi.fi/wfs
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 3
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 5
            timeoutSeconds: 3
